version: '2'

tasks:
  install-goimports:
    cmds:
      - go get -u golang.org/x/tools/cmd/goimports

  goimports:
    cmds:
      - goimports -w pkg cmd

  build:
    cmds:
      - go build -o build/glisp cmd/glisp/main.go